create database PROYECTO_FINAL
GO
USE PROYECTO_FINAL
GO

CREATE TABLE SUCURSAL
(
ID_SUCURSAL INT IDENTITY (1,1) NOT NULL, 
NOMBRE VARCHAR(30), 
DIRECCION VARCHAR(50), 
EMAIL VARCHAR(30),
TELEFONO VARCHAR(10)
PRIMARY KEY (ID_SUCURSAL)
)
SELECT * FROM SUCURSAL


/* TIPO EMPLEADO*/
CREATE TABLE TIPO_EMPLEADO
(
ID_TIPO_EMPLEADO INT IDENTITY (1,1) NOT NULL,
DESCRIPCION VARCHAR(20)
PRIMARY KEY (ID_TIPO_EMPLEADO)
)

SELECT * FROM TIPO_EMPLEADO

CREATE TABLE EDITORIAL
(
ID_EDITORIAL INT IDENTITY (1,1) NOT NULL, 
NOMBRE VARCHAR(30), 
TELEFONO VARCHAR(10),
EMAIL VARCHAR(30)
PRIMARY KEY (ID_EDITORIAL) 
)
SELECT * FROM EDITORIAL

CREATE TABLE AUTOR 
(
ID_AUTOR INT IDENTITY (1,1) NOT NULL,
NOMBRE VARCHAR(30)
PRIMARY KEY (ID_AUTOR)
)
SELECT * FROM AUTOR

CREATE TABLE LIBRO
(
ID_LIBRO INT, 
NOMBRE VARCHAR(30),
ID_AUTOR INT, 
FECHA_PUBLICACION DATE, 
ID_EDITORIAL INT,
COSTO INT
PRIMARY KEY (ID_LIBRO)
FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR,
FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIAL
)
SELECT * FROM LIBRO 

CREATE TABLE INVENTARIO 
(
ID_SUCURSAL INT FOREIGN KEY REFERENCES SUCURSAL,
ID_LIBRO INT, 
CANTIDAD INT
PRIMARY KEY (ID_SUCURSAL, ID_LIBRO)
FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO
)
SELECT * FROM INVENTARIO
 
CREATE TABLE FACTURA
(
ID_FACTURA INT IDENTITY (1,1) NOT NULL, 
FECHA_FAC DATE, 
ID_SUCURSAL INT 
PRIMARY KEY (ID_FACTURA)
FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL 
)
SELECT * FROM FACTURA

CREATE TABLE DETALLE_FACTURA 
(
ID_FACTURA INT FOREIGN KEY REFERENCES FACTURA, 
ID_LIBRO INT, 
CANT_LIBRO INT 
PRIMARY KEY (ID_FACTURA, ID_LIBRO)
FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO
)
SELECT * FROM DETALLE_FACTURA
 
CREATE TABLE EMPLEADO
(
ID_EMPLEADO INT IDENTITY (1,1) NOT NULL, 
NOMBRE VARCHAR(30), 
APPATERNO VARCHAR(20), 
APMATERNO VARCHAR(20),
DIRECCION VARCHAR(50),
SEXO VARCHAR(10), 
FECHA_NAC DATE, 
ID_TIPO_EMPLEADO INT, 
ID_SUCURSAL INT
PRIMARY KEY (ID_EMPLEADO)
FOREIGN KEY (ID_TIPO_EMPLEADO) REFERENCES TIPO_EMPLEADO,
FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL
)
SELECT * FROM EMPLEADO


CREATE TABLE EMAIL_EMPLEADO
(
ID_EMAIL INT IDENTITY (1,1) NOT NULL, 
DESCRIPCION VARCHAR(30), 
ID_EMPLEADO INT
PRIMARY KEY (ID_EMAIL)
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO
)

SELECT * FROM EMAIL_EMPLEADO

CREATE TABLE TELEFONO
(
ID_TELEFONO INT IDENTITY (1,1) NOT NULL, 
TELEFONO VARCHAR(10),
ID_EMPLEADO INT 
PRIMARY KEY (ID_TELEFONO)
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO 
)
SELECT * FROM TELEFONO

 
 
INSERT INTO SUCURSAL VALUES('El gato', 'Delegacion benito juarez no. 325 calle Flor', 'librería.gato@gmail.com', '5526487926')
INSERT INTO SUCURSAL VALUES('El sotano', 'Colona Fraccioamiento Flores Calle 5 no.120', 'libreria.sotano@gmail.com', '559874516')
INSERT INTO SUCURSAL VALUES('El puma', 'Delegacion venustiano carranza calle 15 no.20', 'libreria.puma@gmail.com', '5545921686')
INSERT INTO SUCURSAL VALUES('El conocimiento', 'Delegacion benuto juarez calle 21 no.22', 'conocimiento@gmail.com', '5598642643')
INSERT INTO SUCURSAL VALUES('El paraiso', 'Coyoacan av. San martin no. 325', 'libreria.paraiso@gmail.com', '5598974600')
 SELECT * FROM SUCURSAL


INSERT INTO TIPO_EMPLEADO VALUES('Gerente')
INSERT INTO TIPO_EMPLEADO VALUES('Normal')
INSERT INTO TIPO_EMPLEADO VALUES('Vendedor')
SELECT * FROM TIPO_EMPLEADO

INSERT INTO EMPLEADO VALUES('Kiara Itandehui', 'Cuautle', 'Gonzalez', 'Calle Ebanos Frac. Floresta Mz. 65' , 'FEMENINO', '05-05-1999', 1, 1 )
INSERT INTO EMPLEADO VALUES('Juneri', 'Cuautle', 'Gonzalez', 'Calle Ebanos Frac. Floresta Mz. 65' , 'FEMENINO', '03-03-2002', 2, 3 )
INSERT INTO EMPLEADO VALUES('Gerardo', 'Gutierrez', 'Tellez', 'Calle libertad no. 326 Ecatepec' , 'MASCULINO', '11-02-1999', 2, 2 )
INSERT INTO EMPLEADO VALUES('Issai', 'Mendoza', 'Vazquez', 'Calle amanos Mz 68 LT 8 Texcoco' , 'MASCULINO', '11-02-1999', 1, 4 )
INSERT INTO EMPLEADO VALUES('Alfredo', 'Guzman', 'Velazquez', 'Calle libertad no. 326 Ecatepec' , 'MASCULINO', '03-12-1999', 2, 2 )
SELECT * FROM EMPLEADO



INSERT INTO TELEFONO VALUES('5545920786', 1)
INSERT INTO TELEFONO VALUES('5596490695', 5)
INSERT INTO TELEFONO VALUES('5598784210', 3)

INSERT INTO EDITORIAL VALUES('RA MA', '5589742102', 'editorial.rama@gmail.com', 'nezahualcoyolt calle escondida no. 12')
INSERT INTO EDITORIAL VALUES('Serpiente', '55894715', 'editorial.serpiente@gmail.com', 'calle oriente 4 ')
INSERT INTO EDITORIAL VALUES('El oso', '5526939864', 'editorial.oso@gmail.com', 'calle flores no. 312 delegacion benito juarez')
ALTER TABLE EDITORIAL ADD DIRECCION VARCHAR(50)
SELECT * FROM EDITORIAL


INSERT INTO AUTOR VALUES('J. K. Rowling')
INSERT INTO AUTOR VALUES('J. R. R. Tolkien')
INSERT INTO AUTOR VALUES('John Katzenhbach')
SELECT * FROM AUTOR 

INSERT INTO LIBRO VALUES(1, 'HARRY POTTER', 1 , '01-02-2003',1 , 280)


drop TABLE TIPO_EMPLEADO
SELECT * FROM LIBRO
INSERT INTO LIBRO VALUES(2, 'SEÑOR DE LOS ANILLOS', 2 , '10-20-1999',2 , 350)
INSERT INTO LIBRO VALUES(3, 'PSICOANALISTA', 3 , '04-15-2009',3 , 360)


INSERT INTO FACTURA VALUES('05-11-2019',1 )
INSERT INTO FACTURA VALUES('05-05-2019',2 )
SELECT * FROM FACTURA

INSERT INTO DETALLE_FACTURA VALUES(1, 2, 3)
INSERT INTO DETALLE_FACTURA VALUES(2, 2, 2)
SELECT * FROM DETALLE_FACTURA

INSERT INTO INVENTARIO VALUES(1, 1, 26)
INSERT INTO INVENTARIO VALUES(2, 3, 29)
INSERT INTO INVENTARIO VALUES(1, 2, 30)
INSERT INTO INVENTARIO VALUES(3, 2, 27)
SELECT * FROM INVENTARIO

/*CAMBIA LA CANTIDAD DE LIBRO A 8*/
UPDATE DETALLE_FACTURA SET CANT_LIBRO = 8 WHERE (ID_FACTURA=2) AND (ID_LIBRO=2) 


/*CUENTA CUANTOS EMPLEADOS SON FEMENINOS Y CUANTOS MASCULINOS*/
SELECT COUNT(ID_EMPLEADO) AS NUMERO, SEXO FROM EMPLEADO GROUP BY SEXO 

/*CUENTA CUANTOS EMEPLEADOS HAY EN CADA SUCURSAL*/
SELECT COUNT(ID_EMPLEADO) AS NUMERO, ID_SUCURSAL FROM EMPLEADO GROUP BY ID_SUCURSAL 

/*MUESTRA LOS NOMBRE DE LOS EMPLEADO CON CONCATENACION*/
SELECT NOMBRE + APPATERNO + APMATERNO AS NOMBRE FROM EMPLEADO
SELECT * FROM EMPLEADO


/*SELECCIONA LOS DATOS DEL LIBRO DONDE EL ID SEA 1*/
SELECT * FROM LIBRO WHERE ID_LIBRO=1

/*MUESTRA LA FECHA DE LA PUBLICACION DEL LIBRO*/
SELECT FECHA_PUBLICACION FROM LIBRO WHERE NOMBRE='HARRY POTTER Y LA PIEDRA FILOSOFAL'

/*MUESTRA LA CONCATENACION DEL LIBRO Y COSTO*/
SELECT 'EL ' + NOMBRE + ' CUESTA ' + CAST(COSTO AS VARCHAR (10)) AS DATOS FROM LIBRO 

/*MUESTRA LOS LIBROS QUE ESTEN ENTRE 350 Y 370*/
SELECT NOMBRE, COSTO FROM LIBRO WHERE COSTO BETWEEN 350 AND 370

/*LIBRO CON MENOR COSTO*/
SELECT  MIN(COSTO) AS MENOR_COSTO FROM LIBRO
SELECT * FROM LIBRO


/*MUESTRA LOS DATOS DE LA SUCURSAL EL GATO O EL PUMA*/
SELECT * FROM SUCURSAL WHERE (NOMBRE='EL GATO') OR (NOMBRE='EL PUMA')

/*MUESTA SOLO LOS DATOS DE ID SUCURSAL, NOMBRE Y TELEFONO DE LAS SUCURSALES*/
SELECT ID_SUCURSAL, NOMBRE, TELEFONO FROM SUCURSAL 

/*MUESTRA LOS NOMBRE DE AUTORES QUE DESPUES DEL PRINCIPIO CONTIENEN LA PALABRA Rowling*/
SELECT NOMBRE FROM AUTOR WHERE NOMBRE LIKE '%Rowling'



SELECT 'LA FACTURA ' + CAST(ID_FACTURA AS VARCHAR(5)) + ' CONTIENE EL LIBRO ' + CAST(ID_LIBRO AS VARCHAR(5)) + 'QUE SE VENDIO AL COSTO DE ' + CAST(CANT_LIBRO AS VARCHAR(5)) AS DATOS FROM DETALLE_FACTURA  
SELECT * FROM AUTOR
SELECT * FROM DETALLE_FACTURA



/*MUESTRA TODOS LOS DATOS DE LOS EMPLEADOS, JUNTO CON LA TABLA DE TELEFONO*/
SELECT EMPLEADO.NOMBRE, EMPLEADO.APPATERNO, EMPLEADO.APMATERNO, EMPLEADO.DIRECCION, TELEFONO.TELEFONO FROM EMPLEADO, TELEFONO WHERE EMPLEADO.ID_EMPLEADO = TELEFONO.ID_TELEFONO

/*MUESTRA DATOS DEL LIBRO, AUTOR Y EDITORIAL*/
SELECT LIBRO.ID_LIBRO, LIBRO.NOMBRE, LIBRO.COSTO, AUTOR.NOMBRE AS AUTOR, LIBRO.FECHA_PUBLICACION, EDITORIAL.NOMBRE AS EDITORIAL FROM LIBRO, AUTOR, EDITORIAL WHERE LIBRO.ID_LIBRO = AUTOR.ID_AUTOR AND 
LIBRO.ID_LIBRO= EDITORIAL.ID_EDITORIAL

/*MUESTRA DATOS DE LAS FACTURAS Y  SUCURSALES*/
SELECT  FACTURA.ID_FACTURA, FACTURA.FECHA_FAC, SUCURSAL.NOMBRE AS SUCURSALES FROM FACTURA, SUCURSAL WHERE FACTURA.ID_FACTURA = SUCURSAL.ID_SUCURSAL 
SELECT  FACTURA.ID_FACTURA, FACTURA.FECHA_FAC, SUCURSAL.NOMBRE AS SUCURSALES FROM FACTURA INNER JOIN SUCURSAL ON FACTURA.ID_FACTURA = SUCURSAL.ID_SUCURSAL 

/*MUESTRA DATOS DE LA FACTURA, DETALLE DE LA FACTURA Y LIBRO*/
SELECT DETALLE_FACTURA.ID_FACTURA, FACTURA.FECHA_FAC, LIBRO.NOMBRE AS LIBRO, LIBRO.COSTO, DETALLE_FACTURA.CANT_LIBRO FROM DETALLE_FACTURA, LIBRO, FACTURA
 WHERE DETALLE_FACTURA.ID_FACTURA = FACTURA.ID_FACTURA AND DETALLE_FACTURA.ID_LIBRO = LIBRO.ID_LIBRO

/*FACTURACION DE LOS LIBROS VENDIDO DESDE DETALLE_FACTURA, LIBRO, SUCURSAL Y FACTURA*/
SELECT DETALLE_FACTURA.ID_FACTURA, FACTURA.FECHA_FAC, LIBRO.NOMBRE AS LIBRO, LIBRO.COSTO, DETALLE_FACTURA.CANT_LIBRO, SUCURSAL.NOMBRE AS SUCURSAL  FROM DETALLE_FACTURA, LIBRO, FACTURA, SUCURSAL
 WHERE DETALLE_FACTURA.ID_FACTURA = FACTURA.ID_FACTURA AND DETALLE_FACTURA.ID_LIBRO = LIBRO.ID_LIBRO AND FACTURA.ID_FACTURA = SUCURSAL.ID_SUCURSAL

/*INVENTARIO*/
SELECT INVENTARIO.ID_SUCURSAL, SUCURSAL.NOMBRE AS SUCURSAL, LIBRO.NOMBRE AS LIBRO, AUTOR.NOMBRE AS AUTOR, INVENTARIO.CANTIDAD FROM INVENTARIO, SUCURSAL, LIBRO, AUTOR 
WHERE INVENTARIO.ID_SUCURSAL = SUCURSAL.ID_SUCURSAL AND INVENTARIO.ID_LIBRO = LIBRO.ID_LIBRO AND LIBRO.ID_LIBRO = AUTOR.ID_AUTOR


/*TODOS LOS EMPLEADO QUE NO TIENE EMAIL*/
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO NOT IN (SELECT DISTINCT (ID_EMPLEADO) FROM EMAIL_EMPLEADO)

/*MUESTRA LOS RESULTADOS DE LAS FILAS NO COINCIDENTE Y COINCIDENTES*/
SELECT EMPLEADO.NOMBRE, EMAIL_EMPLEADO.DESCRIPCION FROM EMPLEADO FULL OUTER JOIN EMAIL_EMPLEADO ON EMPLEADO.ID_EMPLEADO = EMAIL_EMPLEADO.ID_EMPLEADO

/*MUESTRA TODOS LOS REGISTROS DE SUCURSAL Y LOS QUE COINCIDEN CON EMPLEADO*/
SELECT SUCURSAL.ID_SUCURSAL, SUCURSAL.NOMBRE, EMPLEADO.NOMBRE FROM SUCURSAL LEFT OUTER JOIN EMPLEADO ON SUCURSAL.ID_SUCURSAL = EMPLEADO.ID_EMPLEADO 

/*TODOS LOS REGISTROS DE LA TABLA LIBRO Y LOS QUE COINCIDEN CON LOS REGISTROS DE AUTOR*/
SELECT AUTOR.NOMBRE, LIBRO.NOMBRE , LIBRO.ID_EDITORIAL, LIBRO.FECHA_PUBLICACION, LIBRO.COSTO FROM AUTOR RIGHT OUTER JOIN LIBRO ON AUTOR.ID_AUTOR = LIBRO.ID_LIBRO 

